---
name: Build and Test

on:
  pull_request:
    branches:
      - master
  release:
    types:
      - published
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: false

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --build-tags integration -p bugs -p unused -D protogetter --timeout=5m

    - name: Test
      run: |
        make test

    - name: Report Coverage to PR
      run: |
        bash <(curl -s https://codecov.io/bash)
      if: github.event_name == 'pull_request'
